before_script:
  - git checkout master
  # - cd js/
  - url="${D_URL}"
  - fullName=${url##*/}
  - fileName=${fullName%%.*}
  - echo ${fileName}
  - fileType=${fullName##*.}
  - echo ${fileType}
  - version=${D_VERSION}

script:
  - curl -o ./${fileType}/${fileName}/${version}/${fullName} --create-dirs ${url}

after_script:
  - pwd
  - ls -l
  # - cd ..
  - git remote -v
  - git branch -v
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add -A
  - git commit -m "${GH_COMMIT}"
  - git push "https://${GH_TOKEN}@${GH_REF}" master
  # - cd -
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/wuyax/cdn.git
   - GH_COMMIT: "set env var"
   - D_URL: "http://mrdoob.github.io/stats.js/build/stats.min.js"
   - D_VERSION: "1.1.1"